ashiq_env/CRUD/CRUD/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'testapp/',include("testapp.urls")),
]

ashiq_env/CRUD/testapp/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'testapp'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    url(r'person/add/$', views.PersonCreate.as_view(), name='person-add'),
    url(r'person/(?P<pk>[0-9]+)/$', views.PersonUpdate.as_view(), name='person-update'),
    url(r'person/(?P<pk>[0-9]+)/delete/$', views.PersonDelete.as_view(), name='person-delete'),
]

ashiq_env/CRUD/testapp/models.py
from django.db import models
from django.views import generic
from django.core.urlresolvers import reverse
from django.views.generic.edit import CreateView, UpdateView, DeleteView


# Create your models here.
class Person(models.Model):
    name = models.CharField(max_length=250)
    country= models.CharField(max_length=500)


    def get_absolute_url(self):
        return reverse('testapp:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name + " - " + self.country


class Description(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    adress = models.CharField(max_length=220)
    mobile_number= models.CharField(max_length=250)
    favorite_food = models.CharField(max_length=250)

    def __str__(self):
        return self.adress+" - "+self.mobile_number+" - "+self.favorite_food


class PersonCreate(CreateView):
    model = Person
    fields = ['name', 'country' ]

ashiq_env/CRUD/testapp/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Person
from django.template import loader

class IndexView(generic.ListView):
    template_name='testapp/index.html'
    context_object_name='all_persons'
    def get_queryset(self):
        return Person.objects.all()

class DetailView(generic.DetailView):
    model=Person
    template_name = 'testapp/detail.html'

class PersonCreate(CreateView):
    model=Person
    fields=['name','country']
class PersonUpdate(UpdateView):
    model=Person
    fields=['name','country' ]
class PersonDelete(DeleteView ):
    model=Person
    success_url=reverse_lazy('testapp:index')

ashiq_env/CRUD/testapp/templates/testapp/base.html
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> </title>

    {% load staticfiles %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'testapp:index' %}">Expo_Ashique</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block persons_active %}{% endblock %}"><a href="{% url 'testapp:index' %}"><span class="fa fa-odnoklassniki" aria-hidden="true"></span>&nbsp; Persons</a></li>
                <li class="{% block descriptions_active %}{% endblock %}"><a href="#"><span class="fa fa-weixin" aria-hidden="true"></span>&nbsp; Descriptions</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{%url 'testapp:person-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Person
                    </a>
                </li>
                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

ashiq_env/CRUD/testapp/templates/testapp/detail.html
{% extends 'testapp/base.html' %}


{% block body %}


<h1>{{person.name}}</h1>
<h1> {{person.country}}</h1>

{% if error_message %}
<p><strong>{{error_message}}</strong> </p>
{%endif%}


    {% csrf_token %}
      {% for description in person.description_set.all %}
          <label for="description{{ forloop.counter }} ">
            <h3>Address: </h3>  {{description.adress}}<br>
            <h3>Mobile Number: </h3>   {{description.mobile_number}}<br>
             <h3>Favorite Food: </h3>  {{description.favorite_food}}<br>

    </label><br>
 {%endfor%}

{% endblock %}

ashiq_env/CRUD/testapp/templates/testapp/form_template.html
 {% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2"  >{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

ashiq_env/CRUD/testapp/templates/testapp/index.html
<!-- path  -->
{% extends 'testapp/base.html' %}


{% block body %}
{% if all_persons %}
<h1>Here is All Person's Informations</h1>
<ul>
    {% for person in all_persons %}
    <li><a href="{%url 'testapp:detail' person.id %}">{{person.name}} </a></li>
<form action="{% url 'testapp:person-delete' person.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="person_id" value="{{ person.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
     <a href="{%url 'testapp:person-update' person.id %}">Edit </a>

    {%endfor%}
</ul>
{% else %}
<h3>You don't have Person Informations</h3>
{%endif%}
{% endblock %}

ashiq_env/CRUD/testapp/templates/testapp/person_form.html
{% extends 'testapp/base.html' %}
{% block title %}Add a New Person{% endblock %}
{% block persons_active%}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Person</h3>
                    {% if error_message %}
                    <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'testapp/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>


    </div>

</div>
{% endblock %}